// Centralized endpoint paths. All on the async v2 API surface.
export const endpoints = {
    register: "/api/v2/auth/register",
    login: "/api/v2/auth/login",
    refresh: "/api/v2/auth/refresh",
    logout: "/api/v2/auth/logout",
    logoutAll: "/api/v2/auth/logout-all",
    sessions: "/api/v2/auth/sessions",
    me: "/api/v2/users/me",
    mePassword: "/api/v2/users/me/password",
    workspaces: "/api/v2/workspaces",
    workspace: (id: string) => `/api/v2/workspaces/${id}`,
    workspaceMembers: (id: string) => `/api/v2/workspaces/${id}/members`,
    workspaceMember: (id: string, memberId: string) => `/api/v2/workspaces/${id}/members/${memberId}`,
    workspaceInvitations: (id: string) => `/api/v2/workspaces/${id}/invitations`,
    invitations: "/api/v2/invitations",
    acceptInvitation: (id: string) => `/api/v2/invitations/${id}/accept`,
    declineInvitation: (id: string) => `/api/v2/invitations/${id}/decline`,
    tree: (workspaceId: string) => `/api/v2/tree?workspace_id=${encodeURIComponent(workspaceId)}`,
    collections: "/api/v2/collections",
    reorderCollections: "/api/v2/collections/reorder",
    collection: (id: string) => `/api/v2/collections/${id}`,
    requests: "/api/v2/requests",
    request: (id: string) => `/api/v2/requests/${id}`,
    duplicateRequest: (id: string) => `/api/v2/requests/${id}/duplicate`,
    moveRequest: (id: string) => `/api/v2/requests/${id}/move`,
    environments: "/api/v2/environments",
    environmentsIn: (workspaceId: string) => `/api/v2/environments?workspace_id=${encodeURIComponent(workspaceId)}`,
    environment: (id: string) => `/api/v2/environments/${id}`,
    identities: "/api/v2/identities",
    identitiesIn: (workspaceId: string) => `/api/v2/identities?workspace_id=${encodeURIComponent(workspaceId)}`,
    identity: (id: string) => `/api/v2/identities/${id}`,
    identityDefault: (id: string) => `/api/v2/identities/${id}/default`,
    proxy: "/api/v2/proxy",
    // Public, IP-rate-limited relay for the landing-page demos (no auth; locked
    // to the /api/v2/guide/* sandbox on the backend).
    proxyPreview: "/api/v2/proxy/preview",
    notifications: "/api/v2/notifications",
    notificationRead: (id: string) => `/api/v2/notifications/${id}/read`,
    notificationsReadAll: "/api/v2/notifications/read-all",
    notification: (id: string) => `/api/v2/notifications/${id}`,
    meta: "/api/v2/meta",
    downloads: "/api/v2/downloads",
    adminDownloads: "/api/v2/admin/downloads",
    adminOverview: "/api/v2/admin/overview",
    adminMetrics: "/api/v2/admin/metrics",
    adminSettings: "/api/v2/admin/settings",
    adminConfig: "/api/v2/admin/config",
    adminPermissions: "/api/v2/admin/permissions",
    adminRoles: "/api/v2/admin/roles",
    adminRole: (id: string) => `/api/v2/admin/roles/${id}`,
    adminUsers: (query?: string) =>
        query ? `/api/v2/admin/users?query=${encodeURIComponent(query)}` : "/api/v2/admin/users",
    adminUserRole: (id: string) => `/api/v2/admin/users/${id}/role`,
    changelog: "/api/v2/changelog",
    changelogLatest: "/api/v2/changelog/latest",
    changelogUpstream: "/api/v2/changelog/upstream",
    adminChangelog: "/api/v2/admin/changelog",
    adminChangelogItem: (id: string) => `/api/v2/admin/changelog/${id}`,
    adminChangelogPublish: (id: string) => `/api/v2/admin/changelog/${id}/publish`,
    adminChangelogUnpublish: (id: string) => `/api/v2/admin/changelog/${id}/unpublish`,
    adminChangelogReorder: "/api/v2/admin/changelog/reorder",
};
